version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    container_name: cookdinnerapi
    restart: unless-stopped